# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Go app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "*"

env:
  RUN_PUSH_JOB: ${{ github.GITHUB_BASE_REF == 'main' }} && ${{ github.ACTION == 'actions/push' }}

jobs:

  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build
      run: |
        go mod download
        go build -v -o ./siiliboard-linux-amd64 ./cmd

  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'
    - name: Build
      run: |
        go mod download
        go build -v -o ./siiliboard-win-amd64.exe ./cmd

  build-docker:
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        echo 'Push job status: ${{ env.RUN_PUSH_JOB }}'
        docker build --tag siiliboard:latest .

    - name: "Push docker image"
      if: ${{ vars.RUN_PUSH_JOB == 'true' }}
      run: |
        echo 'Pushing docker image'
